---

- name: "Criar usuário Drone"
  ansible.builtin.user:
    name: "{{ drone_user }}"
    system: true
    shell: /sbin/nologin
    create_home: false

- name: "Criar diretórios Drone Server"
  ansible.builtin.file:
    path: "{{ drone_data_dir }}/data"
    state: directory
    owner: "{{ drone_user }}"
    group: "{{ drone_group }}"
    mode: '0750'

- name: "Gerar .env do Drone"
  ansible.builtin.template:
    src: drone.env.j2
    dest: "{{ drone_data_dir }}/.env"
    owner: "{{ drone_user }}"
    group: "{{ drone_group }}"
    mode: '0600'

- name: "Instalar unidade systemd do Drone"
  ansible.builtin.template:
    src: drone.service.j2
    dest: /etc/systemd/system/drone.service
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar Drone Server

